#!/usr/bin/env bash

cd "$(dirname "$0")"

# Library values
source "lib/colors.sh"
source "lib/functions.sh"
source "lib/icons.sh"

# Known directories
PLUGIN_DIR="plugins"
ITEM_DIR="items"

# Setting up the general bar appearance and default values
sketchybar \
	--bar "${bar_config[@]}" \
	--default "${default_config[@]}"

# Right
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/weather.sh"

source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/battery.sh"

sketchybar --add bracket group1 brew battery \
	--set group1 "${divider[@]}"



sketchybar --hotload on
sketchybar --update

echo "sketchybar configuation loaded.."